# -*- coding: utf-8 -*-

"""
local settings for Cl4ptr4p project.
Generated by 'Cl4ptr4p startproject' using Flask 1.1.1

For more information on this file, see
README.md
"""

APP_PATH = 'app'
LIB_PATH = 'lib'

ENDPOINT_API = '/api'
HEADER_API_KEY = 'Authorization'
TOKEN_TYPE = 'Bearer'

DEFAULT_CACHE = 'filesystem'
#SESSION_EXPIRE_TIME = 14400  # 4 hours
# SESSION_EXPIRE_TIME = 7890000  # 23 hours 3 meses
SESSION_EXPIRE_TIME = 10000000  # infinito


ALLOW_METHODS = "GET, POST, PUT, DELETE, OPTIONS, PATCH"

# server configurations
DEFAULT_HOST = '0.0.0.0'
DEFAULT_PORT = 6969
DEBUG = True
ACTIVATE_ENV = False
USE_STDERR = True

# Internationalization
TIME_ZONE = 'UTC -5'
STDR_UTC_HOUR = 5
LOCAL_UTC_HOUR = -5

LANGUAGE_CODE = 'en-us'
USE_I18N = True
USE_L10N = True
USE_TZ = True


